In [33]:
import tensorflow as tf
from tensorflow.keras import layers
import json
import numpy as np

num_classes = 6
with open('training.json', 'r') as f:
    data_dict = json.load(f)

obj = {
    "Hand Close": 0,
    "Thumb": 1,
    "Index": 2,
    "Middle": 3,
    "Ring": 4,
    "Pinky": 5
}
    
# extract the x and y data from the JSON dictionary
x_data = [[int(x) for x in data['xs'].values()] for data in data_dict['data']]
y_data = [obj[data['ys']['label']] for data in data_dict['data']]

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_data_norm = scaler.fit_transform(x_data)
#print(x_data_norm)

x_data = np.array(x_data_norm)
y_data = np.array(y_data)

y_data_c = tf.keras.utils.to_categorical(y_data, num_classes)

print(x_data, y_data_c)

#from sklearn.preprocessing import LabelEncoder

#labels = ['Hand Close', 'Thumb', 'Index', 'Middle', 'Ring', 'Pinky']

#encoder = LabelEncoder()
#int_labels = encoder.fit_transform(labels)

#print(encoder, int_labels)


model = tf.keras.Sequential([
    tf.keras.layers.Dense(58, activation='relu', input_shape=(999,)),
    tf.keras.layers.Dense(58, activation='relu'),
    tf.keras.layers.Dense(num_classes, activation='softmax'),
])

# compile the model with a categorical cross-entropy loss function
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

# train the model
model.fit(x_data, y_data_c, epochs=200, batch_size=32)

with open('testing.json', 'r') as f:
    data_dict = json.load(f)
    
x_test = [[int(x) for x in data['xs'].values()] for data in data_dict['data']]
y_test = [obj[data['ys']['label']] for data in data_dict['data']]
y_test_c = tf.keras.utils.to_categorical(y_test, num_classes)
x_test_norm = scaler.fit_transform(x_test)
print(x_test_norm, y_test_c)
predictions = model.predict(x_test_norm)
for i in range(len(predictions)):
    pred_label = np.argmax(predictions[i])
    true_label = y_test[i]
    print(f"Prediction: {pred_label}, True Label: {true_label}")
    
accuracy = model.evaluate(x_test_norm, y_test_c)[1]
print(f"Accuracy: {accuracy}")

[[0.74025974 0.89095745 0.86197917 ... 0.27272727 0.42253521 0.50632911]
 [0.72294372 0.91223404 0.8828125  ... 0.25974026 0.42253521 0.51898734]
 [0.73160173 0.90691489 0.89322917 ... 0.33766234 0.46478873 0.50632911]
 ...
 [0.73376623 0.8962766  0.875      ... 0.37662338 0.42253521 0.44303797]
 [0.72727273 0.89361702 0.8671875  ... 0.2987013  0.50704225 0.44303797]
 [0.73809524 0.89095745 0.88020833 ... 0.31168831 0.43661972 0.40506329]] [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1.

4/4 [==============================] - 0s 5ms/step - loss: 0.6166 - accuracy: 0.8824
Epoch 142/200
4/4 [==============================] - 0s 5ms/step - loss: 0.6014 - accuracy: 0.8922
Epoch 143/200
4/4 [==============================] - 0s 4ms/step - loss: 0.6071 - accuracy: 0.8627
Epoch 144/200
4/4 [==============================] - 0s 5ms/step - loss: 0.6392 - accuracy: 0.8235
Epoch 145/200
4/4 [==============================] - 0s 5ms/step - loss: 0.7242 - accuracy: 0.7843
Epoch 146/200
4/4 [==============================] - 0s 4ms/step - loss: 0.6042 - accuracy: 0.8627
Epoch 147/200
4/4 [==============================] - 0s 3ms/step - loss: 0.6016 - accuracy: 0.8431
Epoch 148/200
4/4 [==============================] - 0s 4ms/step - loss: 0.6174 - accuracy: 0.8529
Epoch 149/200
4/4 [==============================] - 0s 5ms/step - loss: 0.5909 - accuracy: 0.8333
Epoch 150/200
4/4 [==============================] - 0s 5ms/step - loss: 0.5883 - accuracy: 0.8431
Epoch 151/200
4/4 [=====

In [39]:
import json
import numpy as np
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# load the JSON data
num_classes = 6
with open('training.json', 'r') as f:
    data_dict = json.load(f)

obj = {
    "Hand Close": 0,
    "Thumb": 1,
    "Index": 2,
    "Middle": 3,
    "Ring": 4,
    "Pinky": 5
}
    
# extract the x and y data from the JSON dictionary
xs_train = [[int(x) for x in data['xs'].values()] for data in data_dict['data']]
ys_train = [obj[data['ys']['label']] for data in data_dict['data']]
ys_train = tf.keras.utils.to_categorical(ys_train, num_classes)

xs_train = np.array(xs_train)
ys_train = np.array(ys_train)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(xs_train, ys_train, test_size = 0.25, random_state = 0) 

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X = scaler.transform(xs_train)

# define the number of folds
k = 5

# create a KFold object
kf = KFold(n_splits=k, shuffle=True)

# iterate over the folds
for fold, (train_index, test_index) in enumerate(kf.split(x_data_norm)):
    # get the training and test data for this fold
    x_train, x_test = x_data_norm[train_index], x_data_norm[test_index]
    y_train, y_test = y_data_c[train_index], y_data_c[test_index]

    # normalize the data
    x_train = (x_train - x_train.min()) / (x_train.max() - x_train.min())
    x_test = (x_test - x_train.min()) / (x_train.max() - x_train.min())

    # create the model
    model = Sequential([
        tf.keras.layers.Dense(58, activation='relu', input_shape=(999,)),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(58, activation='relu'),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(58, activation='relu'),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(58, activation='relu'),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(58, activation='relu'),
        #tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(58, activation='relu'),
        #tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(num_classes, activation='softmax'),
    ])

    # compile the model
    model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
    
    # train the model on the training data
    model.fit(x_train, y_train, epochs=1000, batch_size=1000, verbose=0)

    # evaluate the model on the test data
    loss, accuracy = model.evaluate(x_test, y_test, batch_size=32, verbose=0)

    # print the test accuracy for this fold
    print(f'Fold {fold+1} Test accuracy: {accuracy:.4f}')


Fold 1 Test accuracy: 0.1429
Fold 2 Test accuracy: 0.2381
Fold 3 Test accuracy: 0.0500
Fold 4 Test accuracy: 0.2000
Fold 5 Test accuracy: 0.3500


In [ ]:
from sklearn.model_selection import StratifiedKFold
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import  SGD
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from scikeras.wrappers import KerasClassifier

# define the input shape
input_shape = (999,)
num_classes = 6

with open('training.json', 'r') as f:
    data_dict = json.load(f)

obj = {
    "Hand Close": 0,
    "Thumb": 1,
    "Index": 2,
    "Middle": 3,
    "Ring": 4,
    "Pinky": 5
}
    
# extract the x and y data from the JSON dictionary
xs_train = [[int(x) for x in data['xs'].values()] for data in data_dict['data']]
ys_train = [obj[data['ys']['label']] for data in data_dict['data']]
ys_train = tf.keras.utils.to_categorical(ys_train, num_classes)

xs_train = np.array(xs_train)
ys_train = np.array(ys_train)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(xs_train, ys_train, test_size = 0.25, random_state = 0) 

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X = scaler.transform(xs_train)


model = Sequential()
model.add(Dense(58, input_shape=input_shape, activation='relu'))
model.add(Dropout(0.1)),
model.add(Dense(58, activation='relu')),
model.add(Dropout(0.1)),
model.add(Dense(58, activation='relu')),
model.add(Dropout(0.1)),
model.add(Dense(58, activation='relu')),
model.add(Dropout(0.1)),
model.add(Dense(58, activation='relu')),
#model.add(Dropout(0.1)),
model.add(Dense(58, activation='relu')),
#model.add(Dropout(0.1)),
model.add(Dense(num_classes, activation='softmax')),
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=1000, batch_size=1000)

i = 0
while i < 0:
    y_pred = model.predict(X_test)
    y_pred_thres = (y_pred > 1)
    y_pred_thres = y_pred_thres * 1
    y_pred2 = y_pred_thres.argmax(axis=1)
    y_test2 = y_test.argmax(axis=1)
    from sllearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test, y_pred2)
    
    from sklearn.metrics import accuracy_score
    accuracy = accuracy_score(y_test2, y_pred2)
    print(f'accuracyis: {acuuracy} when threshold is: {i}')
    i = i + 0.05

y_pred = model.predict(X_test)
y_pred_thres = (y_pred > 0.15)
y_pred_thres = y_pred_thres * 1
y_pred2 = y_pred_thres.argmax(axis=1)
y_test2 = y_test.argmax(axis=1)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test2, y_pred2) 

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test2, y_pred2)

print(f'accuracy is: {accuracy}')

def baseline_model():
    model = Sequential()
    model.add(Dense(58, input_shape=input_shape, activation='relu'))
    model.add(Dropout(0.1)),
    model.add(Dense(58, activation='relu')),
    model.add(Dropout(0.1)),
    model.add(Dense(58, activation='relu')),
    model.add(Dropout(0.1)),
    model.add(Dense(58, activation='relu')),
    model.add(Dropout(0.1)),
    model.add(Dense(58, activation='relu')),
    #model.add(Dropout(0.1)),
    model.add(Dense(58, activation='relu')),
    #model.add(Dropout(0.1)),
    model.add(Dense(num_classes, activation='softmax')),
    sgd = SGD(learning_rate = 0.01, decay = 1e-6, momentum = 0.9, nesterov = True)
    model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
    return model

estimator = KerasClassifier(model=baseline_model, epochs=1000, batch_size=100)

kfold = KFold(n_splits=5, shuffle=True)
results = cross_val_score(estimator, xs_train, ys_train, cv=kfold)
print("Baseline: %.2f (5.2f%%)" % (results.mean() * 100, results.std() * 100))

In [52]:
from scikeras.wrappers import KerasClassifier

In [49]:
pip install scikeras

Note: you may need to restart the kernel to use updated packages.


In [56]:
from sklearn.model_selection import StratifiedKFold
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import  SGD
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from scikeras.wrappers import KerasClassifier

# define the input shape
input_shape = (999,)
num_classes = 6

with open('training.json', 'r') as f:
    data_dict = json.load(f)

obj = {
    "Hand Close": 0,
    "Thumb": 1,
    "Index": 2,
    "Middle": 3,
    "Ring": 4,
    "Pinky": 5
}
    
# extract the x and y data from the JSON dictionary
xs_train = [[int(x) for x in data['xs'].values()] for data in data_dict['data']]
ys_train = [obj[data['ys']['label']] for data in data_dict['data']]
ys_train = tf.keras.utils.to_categorical(ys_train, num_classes)

xs_train = np.array(xs_train)
ys_train = np.array(ys_train)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(xs_train, ys_train, test_size = 0.25, random_state = 0) 

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X = scaler.transform(xs_train)

dim = 999
dropout = 0.1

model = Sequential()
model.add(Dense(dim, input_shape=input_shape, activation='relu'))
model.add(Dropout(dropout)),
model.add(Dense(dim, activation='relu')),
model.add(Dropout(dropout)),
model.add(Dense(dim, activation='relu')),
model.add(Dropout(dropout)),
model.add(Dense(dim, activation='relu')),
model.add(Dropout(dropout)),
model.add(Dense(dim, activation='relu')),
#model.add(Dropout(dropout)),
model.add(Dense(dim, activation='relu')),
#model.add(Dropout(dropout)),
model.add(Dense(num_classes, activation='softmax')),
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=1000, batch_size=1000)

i = 0
while i < 0:
    y_pred = model.predict(X_test)
    y_pred_thres = (y_pred > 1)
    y_pred_thres = y_pred_thres * 1
    y_pred2 = y_pred_thres.argmax(axis=1)
    y_test2 = y_test.argmax(axis=1)
    from sllearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test, y_pred2)
    
    from sklearn.metrics import accuracy_score
    accuracy = accuracy_score(y_test2, y_pred2)
    print(f'accuracyis: {acuuracy} when threshold is: {i}')
    i = i + 0.05

y_pred = model.predict(X_test)
y_pred_thres = (y_pred > 0.15)
y_pred_thres = y_pred_thres * 1
y_pred2 = y_pred_thres.argmax(axis=1)
y_test2 = y_test.argmax(axis=1)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test2, y_pred2) 

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test2, y_pred2)

print(f'accuracy is: {accuracy}')

def baseline_model():
    model = Sequential()
    model.add(Dense(dim, input_shape=input_shape, activation='relu'))
    model.add(Dropout(dropout)),
    model.add(Dense(dim, activation='relu')),
    model.add(Dropout(dropout)),
    model.add(Dense(dim, activation='relu')),
    model.add(Dropout(dropout)),
    model.add(Dense(dim, activation='relu')),
    model.add(Dropout(dropout)),
    model.add(Dense(dim, activation='relu')),
    #model.add(Dropout(dropout)),
    model.add(Dense(dim, activation='relu')),
    #model.add(Dropout(dropout)),
    model.add(Dense(num_classes, activation='softmax')),
    sgd = SGD(learning_rate = 0.01, decay = 1e-6, momentum = 0.9, nesterov = True)
    model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
    return model

estimator = KerasClassifier(model=baseline_model, epochs=1000, batch_size=100)

kfold = KFold(n_splits=5, shuffle=True)
results = cross_val_score(estimator, xs_train, ys_train, cv=kfold)
print("Baseline: %.2f (5.2f%%)" % (results.mean() * 100, results.std() * 100))

Epoch 1/1000
1/1 [==============================] - 2s 2s/step - loss: 1.8183 - accuracy: 0.1447
Epoch 2/1000
1/1 [==============================] - 0s 107ms/step - loss: 2.1377 - accuracy: 0.2105
Epoch 3/1000
1/1 [==============================] - 0s 126ms/step - loss: 1.9003 - accuracy: 0.1842
Epoch 4/1000
1/1 [==============================] - 0s 115ms/step - loss: 1.8135 - accuracy: 0.1974
Epoch 5/1000
1/1 [==============================] - 0s 111ms/step - loss: 1.7926 - accuracy: 0.1974
Epoch 6/1000
1/1 [==============================] - 0s 106ms/step - loss: 1.7712 - accuracy: 0.3026
Epoch 7/1000
1/1 [==============================] - 0s 122ms/step - loss: 1.7751 - accuracy: 0.2237
Epoch 8/1000
1/1 [==============================] - 0s 109ms/step - loss: 1.7780 - accuracy: 0.2105
Epoch 9/1000
1/1 [==============================] - 0s 105ms/step - loss: 1.7851 - accuracy: 0.1711
Epoch 10/1000
1/1 [==============================] - 0s 122ms/step - loss: 1.7752 - accuracy: 0.2763
Ep

1/1 [==============================] - 0s 110ms/step - loss: 0.7469 - accuracy: 0.6842
Epoch 83/1000
1/1 [==============================] - 0s 128ms/step - loss: 0.7732 - accuracy: 0.6842
Epoch 84/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.8091 - accuracy: 0.6711
Epoch 85/1000
1/1 [==============================] - 0s 109ms/step - loss: 0.9054 - accuracy: 0.6447
Epoch 86/1000
1/1 [==============================] - 0s 111ms/step - loss: 1.2468 - accuracy: 0.4868
Epoch 87/1000
1/1 [==============================] - 0s 108ms/step - loss: 1.0088 - accuracy: 0.6447
Epoch 88/1000
1/1 [==============================] - 0s 107ms/step - loss: 2.0002 - accuracy: 0.4342
Epoch 89/1000
1/1 [==============================] - 0s 119ms/step - loss: 0.9618 - accuracy: 0.6316
Epoch 90/1000
1/1 [==============================] - 0s 115ms/step - loss: 1.4236 - accuracy: 0.4605
Epoch 91/1000
1/1 [==============================] - 0s 106ms/step - loss: 1.2506 - accuracy: 0.5000
Epoc

1/1 [==============================] - 0s 118ms/step - loss: 1.0665 - accuracy: 0.6053
Epoch 163/1000
1/1 [==============================] - 0s 123ms/step - loss: 0.8480 - accuracy: 0.6447
Epoch 164/1000
1/1 [==============================] - 0s 120ms/step - loss: 0.9008 - accuracy: 0.6842
Epoch 165/1000
1/1 [==============================] - 0s 126ms/step - loss: 0.8089 - accuracy: 0.6842
Epoch 166/1000
1/1 [==============================] - 0s 112ms/step - loss: 0.8878 - accuracy: 0.6447
Epoch 167/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.8693 - accuracy: 0.6447
Epoch 168/1000
1/1 [==============================] - 0s 118ms/step - loss: 0.6908 - accuracy: 0.7500
Epoch 169/1000
1/1 [==============================] - 0s 115ms/step - loss: 0.9344 - accuracy: 0.6184
Epoch 170/1000
1/1 [==============================] - 0s 112ms/step - loss: 0.8935 - accuracy: 0.6447
Epoch 171/1000
1/1 [==============================] - 0s 112ms/step - loss: 0.7282 - accuracy: 0.

1/1 [==============================] - 0s 117ms/step - loss: 0.4722 - accuracy: 0.8158
Epoch 243/1000
1/1 [==============================] - 0s 126ms/step - loss: 0.1465 - accuracy: 0.9474
Epoch 244/1000
1/1 [==============================] - 0s 124ms/step - loss: 0.2264 - accuracy: 0.8947
Epoch 245/1000
1/1 [==============================] - 0s 119ms/step - loss: 0.3310 - accuracy: 0.7895
Epoch 246/1000
1/1 [==============================] - 0s 123ms/step - loss: 0.3324 - accuracy: 0.8816
Epoch 247/1000
1/1 [==============================] - 0s 139ms/step - loss: 0.3084 - accuracy: 0.8684
Epoch 248/1000
1/1 [==============================] - 0s 118ms/step - loss: 0.2637 - accuracy: 0.8947
Epoch 249/1000
1/1 [==============================] - 0s 125ms/step - loss: 0.2115 - accuracy: 0.9342
Epoch 250/1000
1/1 [==============================] - 0s 127ms/step - loss: 0.2962 - accuracy: 0.8684
Epoch 251/1000
1/1 [==============================] - 0s 119ms/step - loss: 0.3803 - accuracy: 0.

1/1 [==============================] - 0s 114ms/step - loss: 0.7113 - accuracy: 0.7500
Epoch 323/1000
1/1 [==============================] - 0s 118ms/step - loss: 0.6456 - accuracy: 0.7632
Epoch 324/1000
1/1 [==============================] - 0s 115ms/step - loss: 0.6913 - accuracy: 0.7368
Epoch 325/1000
1/1 [==============================] - 0s 121ms/step - loss: 0.8041 - accuracy: 0.7632
Epoch 326/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.7630 - accuracy: 0.7105
Epoch 327/1000
1/1 [==============================] - 0s 121ms/step - loss: 0.8708 - accuracy: 0.7237
Epoch 328/1000
1/1 [==============================] - 0s 121ms/step - loss: 0.4996 - accuracy: 0.8421
Epoch 329/1000
1/1 [==============================] - 0s 117ms/step - loss: 0.7154 - accuracy: 0.6579
Epoch 330/1000
1/1 [==============================] - 0s 115ms/step - loss: 0.6530 - accuracy: 0.7763
Epoch 331/1000
1/1 [==============================] - 0s 114ms/step - loss: 0.4808 - accuracy: 0.

1/1 [==============================] - 0s 118ms/step - loss: 0.3106 - accuracy: 0.8947
Epoch 403/1000
1/1 [==============================] - 0s 117ms/step - loss: 0.3288 - accuracy: 0.8947
Epoch 404/1000
1/1 [==============================] - 0s 126ms/step - loss: 0.0711 - accuracy: 0.9868
Epoch 405/1000
1/1 [==============================] - 0s 121ms/step - loss: 0.1623 - accuracy: 0.9342
Epoch 406/1000
1/1 [==============================] - 0s 118ms/step - loss: 0.3651 - accuracy: 0.8816
Epoch 407/1000
1/1 [==============================] - 0s 118ms/step - loss: 0.1411 - accuracy: 0.9474
Epoch 408/1000
1/1 [==============================] - 0s 134ms/step - loss: 0.2035 - accuracy: 0.9474
Epoch 409/1000
1/1 [==============================] - 0s 124ms/step - loss: 0.1374 - accuracy: 0.9605
Epoch 410/1000
1/1 [==============================] - 0s 115ms/step - loss: 0.1328 - accuracy: 0.9605
Epoch 411/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.1760 - accuracy: 0.

1/1 [==============================] - 0s 123ms/step - loss: 0.0917 - accuracy: 0.9737
Epoch 483/1000
1/1 [==============================] - 0s 115ms/step - loss: 0.2107 - accuracy: 0.9079
Epoch 484/1000
1/1 [==============================] - 0s 112ms/step - loss: 0.0764 - accuracy: 0.9605
Epoch 485/1000
1/1 [==============================] - 0s 129ms/step - loss: 0.2731 - accuracy: 0.8816
Epoch 486/1000
1/1 [==============================] - 0s 112ms/step - loss: 0.2343 - accuracy: 0.9211
Epoch 487/1000
1/1 [==============================] - 0s 112ms/step - loss: 0.3291 - accuracy: 0.8816
Epoch 488/1000
1/1 [==============================] - 0s 116ms/step - loss: 0.1966 - accuracy: 0.9211
Epoch 489/1000
1/1 [==============================] - 0s 126ms/step - loss: 0.1908 - accuracy: 0.9474
Epoch 490/1000
1/1 [==============================] - 0s 111ms/step - loss: 0.3392 - accuracy: 0.9079
Epoch 491/1000
1/1 [==============================] - 0s 111ms/step - loss: 0.2240 - accuracy: 0.

1/1 [==============================] - 0s 117ms/step - loss: 0.1289 - accuracy: 0.9474
Epoch 563/1000
1/1 [==============================] - 0s 122ms/step - loss: 0.1735 - accuracy: 0.9474
Epoch 564/1000
1/1 [==============================] - 0s 115ms/step - loss: 0.1280 - accuracy: 0.9605
Epoch 565/1000
1/1 [==============================] - 0s 112ms/step - loss: 0.2100 - accuracy: 0.9474
Epoch 566/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.1445 - accuracy: 0.9474
Epoch 567/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.1758 - accuracy: 0.9211
Epoch 568/1000
1/1 [==============================] - 0s 118ms/step - loss: 0.2292 - accuracy: 0.9342
Epoch 569/1000
1/1 [==============================] - 0s 121ms/step - loss: 0.0818 - accuracy: 0.9605
Epoch 570/1000
1/1 [==============================] - 0s 111ms/step - loss: 0.1908 - accuracy: 0.9342
Epoch 571/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.2051 - accuracy: 0.

1/1 [==============================] - 0s 133ms/step - loss: 0.1636 - accuracy: 0.9342
Epoch 643/1000
1/1 [==============================] - 0s 120ms/step - loss: 0.3035 - accuracy: 0.8816
Epoch 644/1000
1/1 [==============================] - 0s 127ms/step - loss: 0.0981 - accuracy: 0.9474
Epoch 645/1000
1/1 [==============================] - 0s 128ms/step - loss: 0.2165 - accuracy: 0.9211
Epoch 646/1000
1/1 [==============================] - 0s 122ms/step - loss: 0.1737 - accuracy: 0.9474
Epoch 647/1000
1/1 [==============================] - 0s 118ms/step - loss: 0.2624 - accuracy: 0.9342
Epoch 648/1000
1/1 [==============================] - 0s 126ms/step - loss: 0.1883 - accuracy: 0.9474
Epoch 649/1000
1/1 [==============================] - 0s 118ms/step - loss: 0.4015 - accuracy: 0.8684
Epoch 650/1000
1/1 [==============================] - 0s 133ms/step - loss: 0.1251 - accuracy: 0.9605
Epoch 651/1000
1/1 [==============================] - 0s 115ms/step - loss: 0.2021 - accuracy: 0.

1/1 [==============================] - 0s 126ms/step - loss: 0.0534 - accuracy: 0.9868
Epoch 723/1000
1/1 [==============================] - 0s 129ms/step - loss: 0.0227 - accuracy: 1.0000
Epoch 724/1000
1/1 [==============================] - 0s 118ms/step - loss: 0.0456 - accuracy: 0.9737
Epoch 725/1000
1/1 [==============================] - 0s 118ms/step - loss: 0.0486 - accuracy: 0.9737
Epoch 726/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.0641 - accuracy: 0.9737
Epoch 727/1000
1/1 [==============================] - 0s 112ms/step - loss: 0.0800 - accuracy: 0.9868
Epoch 728/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.0886 - accuracy: 0.9605
Epoch 729/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.0555 - accuracy: 0.9868
Epoch 730/1000
1/1 [==============================] - 0s 115ms/step - loss: 0.0342 - accuracy: 0.9868
Epoch 731/1000
1/1 [==============================] - 0s 125ms/step - loss: 0.0324 - accuracy: 1.

1/1 [==============================] - 0s 153ms/step - loss: 0.1573 - accuracy: 0.9605
Epoch 803/1000
1/1 [==============================] - 0s 120ms/step - loss: 0.1576 - accuracy: 0.9342
Epoch 804/1000
1/1 [==============================] - 0s 111ms/step - loss: 0.3336 - accuracy: 0.8947
Epoch 805/1000
1/1 [==============================] - 0s 121ms/step - loss: 0.2106 - accuracy: 0.9474
Epoch 806/1000
1/1 [==============================] - 0s 125ms/step - loss: 0.3707 - accuracy: 0.8816
Epoch 807/1000
1/1 [==============================] - 0s 116ms/step - loss: 0.1958 - accuracy: 0.9605
Epoch 808/1000
1/1 [==============================] - 0s 123ms/step - loss: 0.2391 - accuracy: 0.8816
Epoch 809/1000
1/1 [==============================] - 0s 134ms/step - loss: 0.4027 - accuracy: 0.8553
Epoch 810/1000
1/1 [==============================] - 0s 124ms/step - loss: 1.9375 - accuracy: 0.5658
Epoch 811/1000
1/1 [==============================] - 0s 113ms/step - loss: 1.7061 - accuracy: 0.

1/1 [==============================] - 0s 122ms/step - loss: 0.5888 - accuracy: 0.7763
Epoch 883/1000
1/1 [==============================] - 0s 120ms/step - loss: 0.5547 - accuracy: 0.8816
Epoch 884/1000
1/1 [==============================] - 0s 114ms/step - loss: 0.6380 - accuracy: 0.7105
Epoch 885/1000
1/1 [==============================] - 0s 111ms/step - loss: 0.6854 - accuracy: 0.7500
Epoch 886/1000
1/1 [==============================] - 0s 112ms/step - loss: 0.4457 - accuracy: 0.9079
Epoch 887/1000
1/1 [==============================] - 0s 112ms/step - loss: 0.4877 - accuracy: 0.8158
Epoch 888/1000
1/1 [==============================] - 0s 115ms/step - loss: 0.4794 - accuracy: 0.7763
Epoch 889/1000
1/1 [==============================] - 0s 114ms/step - loss: 0.4926 - accuracy: 0.7632
Epoch 890/1000
1/1 [==============================] - 0s 131ms/step - loss: 0.5120 - accuracy: 0.7895
Epoch 891/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.5019 - accuracy: 0.

1/1 [==============================] - 0s 113ms/step - loss: 0.4161 - accuracy: 0.8158
Epoch 963/1000
1/1 [==============================] - 0s 137ms/step - loss: 0.4491 - accuracy: 0.8421
Epoch 964/1000
1/1 [==============================] - 0s 111ms/step - loss: 0.4221 - accuracy: 0.8289
Epoch 965/1000
1/1 [==============================] - 0s 112ms/step - loss: 0.4156 - accuracy: 0.8158
Epoch 966/1000
1/1 [==============================] - 0s 115ms/step - loss: 0.5039 - accuracy: 0.7763
Epoch 967/1000
1/1 [==============================] - 0s 122ms/step - loss: 0.5024 - accuracy: 0.7763
Epoch 968/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.3991 - accuracy: 0.8289
Epoch 969/1000
1/1 [==============================] - 0s 115ms/step - loss: 0.3625 - accuracy: 0.8421
Epoch 970/1000
1/1 [==============================] - 0s 113ms/step - loss: 0.4589 - accuracy: 0.8026
Epoch 971/1000
1/1 [==============================] - 0s 121ms/step - loss: 0.4508 - accuracy: 0.

1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1481
Epoch 44/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1481
Epoch 45/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1481
Epoch 46/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1481
Epoch 47/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1481
Epoch 48/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1481
Epoch 49/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1481
Epoch 50/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1481
Epoch 51/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1481
Epoch 52/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1481
Epoch 53/1000
1/1 [=========================

1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1481
Epoch 128/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1481
Epoch 129/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1481
Epoch 130/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1481
Epoch 131/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1481
Epoch 132/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1481
Epoch 133/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1481
Epoch 134/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1481
Epoch 135/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1481
Epoch 136/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1481
Epoch 137/1000
1/1 [===============

1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1481
Epoch 211/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1481
Epoch 212/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1481
Epoch 213/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1481
Epoch 214/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1481
Epoch 215/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1481
Epoch 216/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1481
Epoch 217/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1481
Epoch 218/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1481
Epoch 219/1000
1/1 [==============================] - 0s 56ms/step - loss: nan - accuracy: 0.1481
Epoch 220/1000
1/1 [===============

1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1481
Epoch 294/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1481
Epoch 295/1000
1/1 [==============================] - 0s 83ms/step - loss: nan - accuracy: 0.1481
Epoch 296/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1481
Epoch 297/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1481
Epoch 298/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1481
Epoch 299/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1481
Epoch 300/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1481
Epoch 301/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1481
Epoch 302/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1481
Epoch 303/1000
1/1 [===============

1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1481
Epoch 377/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1481
Epoch 378/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1481
Epoch 379/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1481
Epoch 380/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1481
Epoch 381/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1481
Epoch 382/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1481
Epoch 383/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1481
Epoch 384/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1481
Epoch 385/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1481
Epoch 386/1000
1/1 [===============

1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1481
Epoch 460/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1481
Epoch 461/1000
1/1 [==============================] - 0s 92ms/step - loss: nan - accuracy: 0.1481
Epoch 462/1000
1/1 [==============================] - 0s 88ms/step - loss: nan - accuracy: 0.1481
Epoch 463/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1481
Epoch 464/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1481
Epoch 465/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1481
Epoch 466/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1481
Epoch 467/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1481
Epoch 468/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1481
Epoch 469/1000
1/1 [===============

1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1481
Epoch 543/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1481
Epoch 544/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1481
Epoch 545/1000
1/1 [==============================] - 0s 81ms/step - loss: nan - accuracy: 0.1481
Epoch 546/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1481
Epoch 547/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1481
Epoch 548/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1481
Epoch 549/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1481
Epoch 550/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1481
Epoch 551/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1481
Epoch 552/1000
1/1 [===============

1/1 [==============================] - 0s 81ms/step - loss: nan - accuracy: 0.1481
Epoch 626/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1481
Epoch 627/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1481
Epoch 628/1000
1/1 [==============================] - 0s 80ms/step - loss: nan - accuracy: 0.1481
Epoch 629/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1481
Epoch 630/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1481
Epoch 631/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1481
Epoch 632/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1481
Epoch 633/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1481
Epoch 634/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1481
Epoch 635/1000
1/1 [===============

1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1481
Epoch 709/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1481
Epoch 710/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1481
Epoch 711/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1481
Epoch 712/1000
1/1 [==============================] - 0s 96ms/step - loss: nan - accuracy: 0.1481
Epoch 713/1000
1/1 [==============================] - 0s 76ms/step - loss: nan - accuracy: 0.1481
Epoch 714/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1481
Epoch 715/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1481
Epoch 716/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1481
Epoch 717/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1481
Epoch 718/1000
1/1 [===============

1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1481
Epoch 792/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1481
Epoch 793/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1481
Epoch 794/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1481
Epoch 795/1000
1/1 [==============================] - 0s 83ms/step - loss: nan - accuracy: 0.1481
Epoch 796/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1481
Epoch 797/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1481
Epoch 798/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1481
Epoch 799/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1481
Epoch 800/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1481
Epoch 801/1000
1/1 [===============

1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1481
Epoch 875/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1481
Epoch 876/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1481
Epoch 877/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1481
Epoch 878/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1481
Epoch 879/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1481
Epoch 880/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1481
Epoch 881/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1481
Epoch 882/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1481
Epoch 883/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1481
Epoch 884/1000
1/1 [===============

1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1481
Epoch 958/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1481
Epoch 959/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1481
Epoch 960/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1481
Epoch 961/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1481
Epoch 962/1000
1/1 [==============================] - 0s 79ms/step - loss: nan - accuracy: 0.1481
Epoch 963/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1481
Epoch 964/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1481
Epoch 965/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1481
Epoch 966/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1481
Epoch 967/1000
1/1 [===============

1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1605
Epoch 41/1000
1/1 [==============================] - 0s 57ms/step - loss: nan - accuracy: 0.1605
Epoch 42/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1605
Epoch 43/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1605
Epoch 44/1000
1/1 [==============================] - 0s 60ms/step - loss: nan - accuracy: 0.1605
Epoch 45/1000
1/1 [==============================] - 0s 82ms/step - loss: nan - accuracy: 0.1605
Epoch 46/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1605
Epoch 47/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1605
Epoch 48/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1605
Epoch 49/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1605
Epoch 50/1000
1/1 [=========================

1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1605
Epoch 125/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1605
Epoch 126/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1605
Epoch 127/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1605
Epoch 128/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1605
Epoch 129/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1605
Epoch 130/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1605
Epoch 131/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1605
Epoch 132/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1605
Epoch 133/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1605
Epoch 134/1000
1/1 [===============

1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1605
Epoch 208/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1605
Epoch 209/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1605
Epoch 210/1000
1/1 [==============================] - 0s 76ms/step - loss: nan - accuracy: 0.1605
Epoch 211/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1605
Epoch 212/1000
1/1 [==============================] - 0s 76ms/step - loss: nan - accuracy: 0.1605
Epoch 213/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1605
Epoch 214/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1605
Epoch 215/1000
1/1 [==============================] - 0s 81ms/step - loss: nan - accuracy: 0.1605
Epoch 216/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1605
Epoch 217/1000
1/1 [===============

1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1605
Epoch 291/1000
1/1 [==============================] - 0s 78ms/step - loss: nan - accuracy: 0.1605
Epoch 292/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1605
Epoch 293/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1605
Epoch 294/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1605
Epoch 295/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1605
Epoch 296/1000
1/1 [==============================] - 0s 89ms/step - loss: nan - accuracy: 0.1605
Epoch 297/1000
1/1 [==============================] - 0s 79ms/step - loss: nan - accuracy: 0.1605
Epoch 298/1000
1/1 [==============================] - 0s 79ms/step - loss: nan - accuracy: 0.1605
Epoch 299/1000
1/1 [==============================] - 0s 84ms/step - loss: nan - accuracy: 0.1605
Epoch 300/1000
1/1 [===============

1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1605
Epoch 374/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1605
Epoch 375/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1605
Epoch 376/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1605
Epoch 377/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1605
Epoch 378/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1605
Epoch 379/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1605
Epoch 380/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1605
Epoch 381/1000
1/1 [==============================] - 0s 78ms/step - loss: nan - accuracy: 0.1605
Epoch 382/1000
1/1 [==============================] - 0s 81ms/step - loss: nan - accuracy: 0.1605
Epoch 383/1000
1/1 [===============

1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1605
Epoch 457/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1605
Epoch 458/1000
1/1 [==============================] - 0s 59ms/step - loss: nan - accuracy: 0.1605
Epoch 459/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1605
Epoch 460/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1605
Epoch 461/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1605
Epoch 462/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1605
Epoch 463/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1605
Epoch 464/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1605
Epoch 465/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1605
Epoch 466/1000
1/1 [===============

1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1605
Epoch 540/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1605
Epoch 541/1000
1/1 [==============================] - 0s 59ms/step - loss: nan - accuracy: 0.1605
Epoch 542/1000
1/1 [==============================] - 0s 60ms/step - loss: nan - accuracy: 0.1605
Epoch 543/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1605
Epoch 544/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1605
Epoch 545/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1605
Epoch 546/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1605
Epoch 547/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1605
Epoch 548/1000
1/1 [==============================] - 0s 81ms/step - loss: nan - accuracy: 0.1605
Epoch 549/1000
1/1 [===============

1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1605
Epoch 623/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1605
Epoch 624/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1605
Epoch 625/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1605
Epoch 626/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1605
Epoch 627/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1605
Epoch 628/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1605
Epoch 629/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1605
Epoch 630/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1605
Epoch 631/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1605
Epoch 632/1000
1/1 [===============

1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1605
Epoch 706/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1605
Epoch 707/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1605
Epoch 708/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1605
Epoch 709/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1605
Epoch 710/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1605
Epoch 711/1000
1/1 [==============================] - 0s 78ms/step - loss: nan - accuracy: 0.1605
Epoch 712/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1605
Epoch 713/1000
1/1 [==============================] - 0s 79ms/step - loss: nan - accuracy: 0.1605
Epoch 714/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1605
Epoch 715/1000
1/1 [===============

1/1 [==============================] - 0s 58ms/step - loss: nan - accuracy: 0.1605
Epoch 789/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1605
Epoch 790/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1605
Epoch 791/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1605
Epoch 792/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1605
Epoch 793/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1605
Epoch 794/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1605
Epoch 795/1000
1/1 [==============================] - 0s 80ms/step - loss: nan - accuracy: 0.1605
Epoch 796/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1605
Epoch 797/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1605
Epoch 798/1000
1/1 [===============

1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1605
Epoch 872/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1605
Epoch 873/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1605
Epoch 874/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1605
Epoch 875/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1605
Epoch 876/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1605
Epoch 877/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1605
Epoch 878/1000
1/1 [==============================] - 0s 79ms/step - loss: nan - accuracy: 0.1605
Epoch 879/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1605
Epoch 880/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1605
Epoch 881/1000
1/1 [===============

1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1605
Epoch 955/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1605
Epoch 956/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1605
Epoch 957/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1605
Epoch 958/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1605
Epoch 959/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1605
Epoch 960/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1605
Epoch 961/1000
1/1 [==============================] - 0s 86ms/step - loss: nan - accuracy: 0.1605
Epoch 962/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1605
Epoch 963/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1605
Epoch 964/1000
1/1 [===============

1/1 [==============================] - 0s 77ms/step - loss: nan - accuracy: 0.1829
Epoch 38/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1829
Epoch 39/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 40/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 41/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1829
Epoch 42/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1829
Epoch 43/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1829
Epoch 44/1000
1/1 [==============================] - 0s 81ms/step - loss: nan - accuracy: 0.1829
Epoch 45/1000
1/1 [==============================] - 0s 79ms/step - loss: nan - accuracy: 0.1829
Epoch 46/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1829
Epoch 47/1000
1/1 [=========================

1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 122/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 123/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1829
Epoch 124/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 125/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 126/1000
1/1 [==============================] - 0s 91ms/step - loss: nan - accuracy: 0.1829
Epoch 127/1000
1/1 [==============================] - 0s 78ms/step - loss: nan - accuracy: 0.1829
Epoch 128/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 129/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1829
Epoch 130/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1829
Epoch 131/1000
1/1 [===============

1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 205/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 206/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 207/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 208/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1829
Epoch 209/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1829
Epoch 210/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 211/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 212/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1829
Epoch 213/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 214/1000
1/1 [===============

1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 288/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1829
Epoch 289/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1829
Epoch 290/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 291/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 292/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 293/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 294/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 295/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 296/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 297/1000
1/1 [===============

1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 371/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 372/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 373/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 374/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 375/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 376/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 377/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 378/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 379/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1829
Epoch 380/1000
1/1 [===============

1/1 [==============================] - 0s 82ms/step - loss: nan - accuracy: 0.1829
Epoch 454/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 455/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 456/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 457/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 458/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 459/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1829
Epoch 460/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 461/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 462/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 463/1000
1/1 [===============

1/1 [==============================] - 0s 76ms/step - loss: nan - accuracy: 0.1829
Epoch 537/1000
1/1 [==============================] - 0s 60ms/step - loss: nan - accuracy: 0.1829
Epoch 538/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 539/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1829
Epoch 540/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 541/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 542/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 543/1000
1/1 [==============================] - 0s 79ms/step - loss: nan - accuracy: 0.1829
Epoch 544/1000
1/1 [==============================] - 0s 76ms/step - loss: nan - accuracy: 0.1829
Epoch 545/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1829
Epoch 546/1000
1/1 [===============

1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 620/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 621/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 622/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1829
Epoch 623/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1829
Epoch 624/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 625/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1829
Epoch 626/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 627/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1829
Epoch 628/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1829
Epoch 629/1000
1/1 [===============

1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1829
Epoch 703/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1829
Epoch 704/1000
1/1 [==============================] - 0s 78ms/step - loss: nan - accuracy: 0.1829
Epoch 705/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 706/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1829
Epoch 707/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 708/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1829
Epoch 709/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 710/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 711/1000
1/1 [==============================] - 0s 78ms/step - loss: nan - accuracy: 0.1829
Epoch 712/1000
1/1 [===============

1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 786/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 787/1000
1/1 [==============================] - 0s 80ms/step - loss: nan - accuracy: 0.1829
Epoch 788/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1829
Epoch 789/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 790/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1829
Epoch 791/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 792/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 793/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 794/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1829
Epoch 795/1000
1/1 [===============

1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 869/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1829
Epoch 870/1000
1/1 [==============================] - 0s 78ms/step - loss: nan - accuracy: 0.1829
Epoch 871/1000
1/1 [==============================] - 0s 78ms/step - loss: nan - accuracy: 0.1829
Epoch 872/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1829
Epoch 873/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1829
Epoch 874/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 875/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 876/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1829
Epoch 877/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 878/1000
1/1 [===============

1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1829
Epoch 952/1000
1/1 [==============================] - 0s 76ms/step - loss: nan - accuracy: 0.1829
Epoch 953/1000
1/1 [==============================] - 0s 77ms/step - loss: nan - accuracy: 0.1829
Epoch 954/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1829
Epoch 955/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 956/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 957/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1829
Epoch 958/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 959/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1829
Epoch 960/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 961/1000
1/1 [===============

1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1829
Epoch 35/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 36/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 37/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1829
Epoch 38/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 39/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1829
Epoch 40/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 41/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1829
Epoch 42/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 43/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1829
Epoch 44/1000
1/1 [=========================

1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 119/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1829
Epoch 120/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1829
Epoch 121/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 122/1000
1/1 [==============================] - 0s 95ms/step - loss: nan - accuracy: 0.1829
Epoch 123/1000
1/1 [==============================] - 0s 78ms/step - loss: nan - accuracy: 0.1829
Epoch 124/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 125/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1829
Epoch 126/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 127/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 128/1000
1/1 [===============

1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1829
Epoch 202/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 203/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 204/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 205/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1829
Epoch 206/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1829
Epoch 207/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1829
Epoch 208/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 209/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 210/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 211/1000
1/1 [===============

1/1 [==============================] - 0s 56ms/step - loss: nan - accuracy: 0.1829
Epoch 285/1000
1/1 [==============================] - 0s 59ms/step - loss: nan - accuracy: 0.1829
Epoch 286/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 287/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1829
Epoch 288/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1829
Epoch 289/1000
1/1 [==============================] - 0s 60ms/step - loss: nan - accuracy: 0.1829
Epoch 290/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 291/1000
1/1 [==============================] - 0s 77ms/step - loss: nan - accuracy: 0.1829
Epoch 292/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1829
Epoch 293/1000
1/1 [==============================] - 0s 60ms/step - loss: nan - accuracy: 0.1829
Epoch 294/1000
1/1 [===============

1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 368/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1829
Epoch 369/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1829
Epoch 370/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 371/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 372/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 373/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1829
Epoch 374/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1829
Epoch 375/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1829
Epoch 376/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1829
Epoch 377/1000
1/1 [===============

1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 451/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 452/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 453/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 454/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 455/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 456/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 457/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 458/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1829
Epoch 459/1000
1/1 [==============================] - 0s 76ms/step - loss: nan - accuracy: 0.1829
Epoch 460/1000
1/1 [===============

1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1829
Epoch 534/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1829
Epoch 535/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 536/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 537/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1829
Epoch 538/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 539/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 540/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 541/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 542/1000
1/1 [==============================] - 0s 76ms/step - loss: nan - accuracy: 0.1829
Epoch 543/1000
1/1 [===============

1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1829
Epoch 617/1000
1/1 [==============================] - 0s 77ms/step - loss: nan - accuracy: 0.1829
Epoch 618/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 619/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 620/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 621/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 622/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 623/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 624/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1829
Epoch 625/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1829
Epoch 626/1000
1/1 [===============

1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 700/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1829
Epoch 701/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1829
Epoch 702/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 703/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 704/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 705/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 706/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 707/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 708/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1829
Epoch 709/1000
1/1 [===============

1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1829
Epoch 783/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 784/1000
1/1 [==============================] - 0s 59ms/step - loss: nan - accuracy: 0.1829
Epoch 785/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 786/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 787/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 788/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 789/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1829
Epoch 790/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 791/1000
1/1 [==============================] - 0s 58ms/step - loss: nan - accuracy: 0.1829
Epoch 792/1000
1/1 [===============

1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 866/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 867/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 868/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 869/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 870/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 871/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1829
Epoch 872/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1829
Epoch 873/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 874/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 875/1000
1/1 [===============

1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1829
Epoch 949/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 950/1000
1/1 [==============================] - 0s 60ms/step - loss: nan - accuracy: 0.1829
Epoch 951/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 952/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1829
Epoch 953/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1829
Epoch 954/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 955/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 956/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1829
Epoch 957/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1829
Epoch 958/1000
1/1 [===============

1/1 [==============================] - 0s 76ms/step - loss: nan - accuracy: 0.1585
Epoch 32/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1585
Epoch 33/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1585
Epoch 34/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1585
Epoch 35/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1585
Epoch 36/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1585
Epoch 37/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 38/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1585
Epoch 39/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 40/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1585
Epoch 41/1000
1/1 [=========================

1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1585
Epoch 116/1000
1/1 [==============================] - 0s 78ms/step - loss: nan - accuracy: 0.1585
Epoch 117/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1585
Epoch 118/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1585
Epoch 119/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1585
Epoch 120/1000
1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1585
Epoch 121/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 122/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1585
Epoch 123/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 124/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1585
Epoch 125/1000
1/1 [===============

1/1 [==============================] - 0s 76ms/step - loss: nan - accuracy: 0.1585
Epoch 199/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1585
Epoch 200/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 201/1000
1/1 [==============================] - 0s 85ms/step - loss: nan - accuracy: 0.1585
Epoch 202/1000
1/1 [==============================] - 0s 83ms/step - loss: nan - accuracy: 0.1585
Epoch 203/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1585
Epoch 204/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 205/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 206/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1585
Epoch 207/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1585
Epoch 208/1000
1/1 [===============

1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 282/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1585
Epoch 283/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1585
Epoch 284/1000
1/1 [==============================] - 0s 74ms/step - loss: nan - accuracy: 0.1585
Epoch 285/1000
1/1 [==============================] - 0s 76ms/step - loss: nan - accuracy: 0.1585
Epoch 286/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 287/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 288/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1585
Epoch 289/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1585
Epoch 290/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 291/1000
1/1 [===============

1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1585
Epoch 365/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1585
Epoch 366/1000
1/1 [==============================] - 0s 60ms/step - loss: nan - accuracy: 0.1585
Epoch 367/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1585
Epoch 368/1000
1/1 [==============================] - 0s 77ms/step - loss: nan - accuracy: 0.1585
Epoch 369/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 370/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1585
Epoch 371/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 372/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 373/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 374/1000
1/1 [===============

1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1585
Epoch 448/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1585
Epoch 449/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1585
Epoch 450/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1585
Epoch 451/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 452/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1585
Epoch 453/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1585
Epoch 454/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 455/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 456/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1585
Epoch 457/1000
1/1 [===============

1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1585
Epoch 531/1000
1/1 [==============================] - 0s 61ms/step - loss: nan - accuracy: 0.1585
Epoch 532/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 533/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 534/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1585
Epoch 535/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 536/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 537/1000
1/1 [==============================] - 0s 84ms/step - loss: nan - accuracy: 0.1585
Epoch 538/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 539/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 540/1000
1/1 [===============

1/1 [==============================] - 0s 66ms/step - loss: nan - accuracy: 0.1585
Epoch 614/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 615/1000
1/1 [==============================] - 0s 59ms/step - loss: nan - accuracy: 0.1585
Epoch 616/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1585
Epoch 617/1000
1/1 [==============================] - 0s 64ms/step - loss: nan - accuracy: 0.1585
Epoch 618/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1585
Epoch 619/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1585
Epoch 620/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1585
Epoch 621/1000
1/1 [==============================] - 0s 65ms/step - loss: nan - accuracy: 0.1585
Epoch 622/1000
1/1 [==============================] - 0s 62ms/step - loss: nan - accuracy: 0.1585
Epoch 623/1000
1/1 [===============

1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1585
Epoch 697/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1585
Epoch 698/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1585
Epoch 699/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1585
Epoch 700/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1585
Epoch 701/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 702/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1585
Epoch 703/1000
1/1 [==============================] - 0s 80ms/step - loss: nan - accuracy: 0.1585
Epoch 704/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1585
Epoch 705/1000
1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1585
Epoch 706/1000
1/1 [===============

1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 780/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1585
Epoch 781/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 782/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1585
Epoch 783/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 784/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 785/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1585
Epoch 786/1000
1/1 [==============================] - 0s 67ms/step - loss: nan - accuracy: 0.1585
Epoch 787/1000
1/1 [==============================] - 0s 76ms/step - loss: nan - accuracy: 0.1585
Epoch 788/1000
1/1 [==============================] - 0s 78ms/step - loss: nan - accuracy: 0.1585
Epoch 789/1000
1/1 [===============

1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1585
Epoch 863/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1585
Epoch 864/1000
1/1 [==============================] - 0s 75ms/step - loss: nan - accuracy: 0.1585
Epoch 865/1000
1/1 [==============================] - 0s 72ms/step - loss: nan - accuracy: 0.1585
Epoch 866/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 867/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 868/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1585
Epoch 869/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 870/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1585
Epoch 871/1000
1/1 [==============================] - 0s 73ms/step - loss: nan - accuracy: 0.1585
Epoch 872/1000
1/1 [===============

1/1 [==============================] - 0s 63ms/step - loss: nan - accuracy: 0.1585
Epoch 946/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 947/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 948/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1585
Epoch 949/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 950/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1585
Epoch 951/1000
1/1 [==============================] - 0s 68ms/step - loss: nan - accuracy: 0.1585
Epoch 952/1000
1/1 [==============================] - 0s 70ms/step - loss: nan - accuracy: 0.1585
Epoch 953/1000
1/1 [==============================] - 0s 71ms/step - loss: nan - accuracy: 0.1585
Epoch 954/1000
1/1 [==============================] - 0s 69ms/step - loss: nan - accuracy: 0.1585
Epoch 955/1000
1/1 [===============

TypeError: not all arguments converted during string formatting