In [1]:
import tensorflow as tf
from tensorflow.keras import layers
import json
import numpy as np

num_classes = 6
with open('training.json', 'r') as f:
    data_dict = json.load(f)

obj = {
    "Hand Close": 0,
    "Thumb": 1,
    "Index": 2,
    "Middle": 3,
    "Ring": 4,
    "Pinky": 5
}
    
# extract the x and y data from the JSON dictionary
x_data = [[int(x) for x in data['xs'].values()] for data in data_dict['data']]
y_data = [obj[data['ys']['label']] for data in data_dict['data']]

print(x_data)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_data_norm = scaler.fit_transform(x_data)
#print(x_data_norm)

x_data = np.array(x_data_norm)
y_data = np.array(y_data)

y_data_c = tf.keras.utils.to_categorical(y_data, num_classes)

print(x_data, y_data_c)

#from sklearn.preprocessing import LabelEncoder

#labels = ['Hand Close', 'Thumb', 'Index', 'Middle', 'Ring', 'Pinky']

#encoder = LabelEncoder()
#int_labels = encoder.fit_transform(labels)

#print(encoder, int_labels)


model = tf.keras.Sequential([
    tf.keras.layers.Dense(999, activation='relu', input_shape=(999,)),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(999, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(num_classes, activation='softmax'),
])

# compile the model with a categorical cross-entropy loss function
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

# train the model
#model.fit(x_data, y_data_c, epochs=1000, batch_size=1000)

with open('testing.json', 'r') as f:
    data_dict = json.load(f)
    
x_test = [[int(x) for x in data['xs'].values()] for data in data_dict['data']]
y_test = [obj[data['ys']['label']] for data in data_dict['data']]
y_test_c = tf.keras.utils.to_categorical(y_test, num_classes)
x_test_norm = scaler.fit_transform(x_test)
print(x_test_norm, y_test_c)
predictions = model.predict(x_test_norm)
for i in range(len(predictions)):
    pred_label = np.argmax(predictions[i])
    true_label = y_test[i]
    print(f"Prediction: {pred_label}, True Label: {true_label}")
    
accuracy = model.evaluate(x_test_norm, y_test_c)[1]
print(f"Accuracy: {accuracy}")

[[342, 335, 331, 339, 338, 338, 334, 338, 337, 332, 335, 341, 337, 330, 338, 342, 336, 332, 334, 339, 334, 332, 342, 342, 337, 330, 337, 338, 335, 337, 339, 337, 332, 334, 342, 337, 333, 341, 342, 331, 334, 342, 347, 332, 329, 342, 343, 331, 332, 342, 345, 332, 332, 339, 337, 336, 338, 343, 330, 329, 339, 341, 338, 334, 336, 338, 334, 339, 344, 338, 329, 335, 344, 337, 332, 334, 340, 341, 330, 334, 339, 334, 334, 344, 340, 330, 332, 344, 343, 332, 332, 338, 339, 335, 338, 341, 339, 332, 333, 339, 337, 334, 337, 339, 338, 331, 338, 341, 334, 336, 339, 337, 329, 334, 345, 342, 330, 335, 346, 339, 331, 337, 347, 334, 330, 340, 344, 338, 331, 338, 340, 335, 337, 344, 341, 334, 338, 341, 335, 329, 338, 344, 336, 333, 342, 349, 336, 327, 336, 338, 333, 335, 344, 342, 342, 334, 334, 336, 332, 336, 343, 339, 334, 341, 345, 333, 336, 339, 340, 334, 337, 345, 340, 332, 336, 342, 342, 334, 337, 346, 337, 332, 338, 343, 339, 331, 337, 342, 343, 339, 338, 338, 332, 336, 343, 340, 336, 336, 341, 340

[[0.74025974 0.89095745 0.86197917 ... 0.27272727 0.42253521 0.50632911]
 [0.72294372 0.91223404 0.8828125  ... 0.25974026 0.42253521 0.51898734]
 [0.73160173 0.90691489 0.89322917 ... 0.33766234 0.46478873 0.50632911]
 ...
 [0.73376623 0.8962766  0.875      ... 0.37662338 0.42253521 0.44303797]
 [0.72727273 0.89361702 0.8671875  ... 0.2987013  0.50704225 0.44303797]
 [0.73809524 0.89095745 0.88020833 ... 0.31168831 0.43661972 0.40506329]] [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1.