In [1]:
import tensorflow as tf
from tensorflow.keras import layers
import json
import numpy as np

num_classes = 6
with open('training.json', 'r') as f:
    data_dict = json.load(f)

obj = {
    "Hand Close": 0,
    "Thumb": 1,
    "Index": 2,
    "Middle": 3,
    "Ring": 4,
    "Pinky": 5
}
    
# extract the x and y data from the JSON dictionary
x_data = [[int(x) for x in data['xs'].values()] for data in data_dict['data']]
y_data = [obj[data['ys']['label']] for data in data_dict['data']]

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_data_norm = scaler.fit_transform(x_data)
#print(x_data_norm)

x_data = np.array(x_data_norm)
y_data = np.array(y_data)

y_data_c = tf.keras.utils.to_categorical(y_data, num_classes)

print(x_data, y_data_c)

#from sklearn.preprocessing import LabelEncoder

#labels = ['Hand Close', 'Thumb', 'Index', 'Middle', 'Ring', 'Pinky']

#encoder = LabelEncoder()
#int_labels = encoder.fit_transform(labels)

#print(encoder, int_labels)


model = tf.keras.Sequential([
    tf.keras.layers.Dense(58, activation='relu', input_shape=(999,)),
    tf.keras.layers.Dense(58, activation='relu'),
    tf.keras.layers.Dense(num_classes, activation='softmax'),
])

# compile the model with a categorical cross-entropy loss function
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

# train the model
model.fit(x_data, y_data_c, epochs=200, batch_size=32)

with open('testing.json', 'r') as f:
    data_dict = json.load(f)
    
x_test = [[int(x) for x in data['xs'].values()] for data in data_dict['data']]
y_test = [obj[data['ys']['label']] for data in data_dict['data']]
y_test_c = tf.keras.utils.to_categorical(y_test, num_classes)
x_test_norm = scaler.fit_transform(x_test)
print(x_test_norm, y_test_c)
predictions = model.predict(x_test_norm)
for i in range(len(predictions)):
    pred_label = np.argmax(predictions[i])
    true_label = y_test[i]
    print(f"Prediction: {pred_label}, True Label: {true_label}")
    
accuracy = model.evaluate(x_test_norm, y_test_c)[1]
print(f"Accuracy: {accuracy}")

[[0.74025974 0.89095745 0.86197917 ... 0.27272727 0.42253521 0.50632911]
 [0.72294372 0.91223404 0.8828125  ... 0.25974026 0.42253521 0.51898734]
 [0.73160173 0.90691489 0.89322917 ... 0.33766234 0.46478873 0.50632911]
 ...
 [0.73376623 0.8962766  0.875      ... 0.37662338 0.42253521 0.44303797]
 [0.72727273 0.89361702 0.8671875  ... 0.2987013  0.50704225 0.44303797]
 [0.73809524 0.89095745 0.88020833 ... 0.31168831 0.43661972 0.40506329]] [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1.

4/4 [==============================] - 0s 6ms/step - loss: 1.2649 - accuracy: 0.5392
Epoch 59/200
4/4 [==============================] - 0s 2ms/step - loss: 1.3194 - accuracy: 0.5196
Epoch 60/200
4/4 [==============================] - 0s 5ms/step - loss: 1.2683 - accuracy: 0.5098
Epoch 61/200
4/4 [==============================] - 0s 4ms/step - loss: 1.2522 - accuracy: 0.6176
Epoch 62/200
4/4 [==============================] - 0s 5ms/step - loss: 1.2243 - accuracy: 0.6373
Epoch 63/200
4/4 [==============================] - 0s 3ms/step - loss: 1.2426 - accuracy: 0.5784
Epoch 64/200
4/4 [==============================] - 0s 5ms/step - loss: 1.2333 - accuracy: 0.5392
Epoch 65/200
4/4 [==============================] - 0s 4ms/step - loss: 1.2647 - accuracy: 0.5686
Epoch 66/200
4/4 [==============================] - 0s 3ms/step - loss: 1.2856 - accuracy: 0.5784
Epoch 67/200
4/4 [==============================] - 0s 4ms/step - loss: 1.2025 - accuracy: 0.5686
Epoch 68/200
4/4 [===============

4/4 [==============================] - 0s 6ms/step - loss: 0.5397 - accuracy: 0.8922
Epoch 142/200
4/4 [==============================] - 0s 8ms/step - loss: 0.5132 - accuracy: 0.8824
Epoch 143/200
4/4 [==============================] - 0s 6ms/step - loss: 0.4875 - accuracy: 0.9216
Epoch 144/200
4/4 [==============================] - 0s 4ms/step - loss: 0.4937 - accuracy: 0.9020
Epoch 145/200
4/4 [==============================] - 0s 4ms/step - loss: 0.4920 - accuracy: 0.8922
Epoch 146/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4690 - accuracy: 0.9020
Epoch 147/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4910 - accuracy: 0.8627
Epoch 148/200
4/4 [==============================] - 0s 5ms/step - loss: 0.5581 - accuracy: 0.8627
Epoch 149/200
4/4 [==============================] - 0s 2ms/step - loss: 0.6286 - accuracy: 0.7941
Epoch 150/200
4/4 [==============================] - 0s 4ms/step - loss: 0.5905 - accuracy: 0.7745
Epoch 151/200
4/4 [=====

In [39]:
import json
import numpy as np
from sklearn.model_selection import KFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# load the JSON data
num_classes = 6
with open('training.json', 'r') as f:
    data_dict = json.load(f)

obj = {
    "Hand Close": 0,
    "Thumb": 1,
    "Index": 2,
    "Middle": 3,
    "Ring": 4,
    "Pinky": 5
}
    
# extract the x and y data from the JSON dictionary
xs_train = [[int(x) for x in data['xs'].values()] for data in data_dict['data']]
ys_train = [obj[data['ys']['label']] for data in data_dict['data']]
ys_train = tf.keras.utils.to_categorical(ys_train, num_classes)

xs_train = np.array(xs_train)
ys_train = np.array(ys_train)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(xs_train, ys_train, test_size = 0.25, random_state = 0) 

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X = scaler.transform(xs_train)

# define the number of folds
k = 5

# create a KFold object
kf = KFold(n_splits=k, shuffle=True)

# iterate over the folds
for fold, (train_index, test_index) in enumerate(kf.split(x_data_norm)):
    # get the training and test data for this fold
    x_train, x_test = x_data_norm[train_index], x_data_norm[test_index]
    y_train, y_test = y_data_c[train_index], y_data_c[test_index]

    # normalize the data
    x_train = (x_train - x_train.min()) / (x_train.max() - x_train.min())
    x_test = (x_test - x_train.min()) / (x_train.max() - x_train.min())

    # create the model
    model = Sequential([
        tf.keras.layers.Dense(58, activation='relu', input_shape=(999,)),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(58, activation='relu'),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(58, activation='relu'),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(58, activation='relu'),
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(58, activation='relu'),
        #tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(58, activation='relu'),
        #tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(num_classes, activation='softmax'),
    ])

    # compile the model
    model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
    
    # train the model on the training data
    model.fit(x_train, y_train, epochs=1000, batch_size=1000, verbose=0)

    # evaluate the model on the test data
    loss, accuracy = model.evaluate(x_test, y_test, batch_size=32, verbose=0)

    # print the test accuracy for this fold
    print(f'Fold {fold+1} Test accuracy: {accuracy:.4f}')


Fold 1 Test accuracy: 0.1429
Fold 2 Test accuracy: 0.2381
Fold 3 Test accuracy: 0.0500
Fold 4 Test accuracy: 0.2000
Fold 5 Test accuracy: 0.3500


In [ ]:
from sklearn.model_selection import StratifiedKFold
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import  SGD
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from scikeras.wrappers import KerasClassifier

# define the input shape
input_shape = (999,)
num_classes = 6

with open('training.json', 'r') as f:
    data_dict = json.load(f)

obj = {
    "Hand Close": 0,
    "Thumb": 1,
    "Index": 2,
    "Middle": 3,
    "Ring": 4,
    "Pinky": 5
}
    
# extract the x and y data from the JSON dictionary
xs_train = [[int(x) for x in data['xs'].values()] for data in data_dict['data']]
ys_train = [obj[data['ys']['label']] for data in data_dict['data']]
ys_train = tf.keras.utils.to_categorical(ys_train, num_classes)

xs_train = np.array(xs_train)
ys_train = np.array(ys_train)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(xs_train, ys_train, test_size = 0.25, random_state = 0) 

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X = scaler.transform(xs_train)


model = Sequential()
model.add(Dense(58, input_shape=input_shape, activation='relu'))
model.add(Dropout(0.1)),
model.add(Dense(58, activation='relu')),
model.add(Dropout(0.1)),
model.add(Dense(58, activation='relu')),
model.add(Dropout(0.1)),
model.add(Dense(58, activation='relu')),
model.add(Dropout(0.1)),
model.add(Dense(58, activation='relu')),
#model.add(Dropout(0.1)),
model.add(Dense(58, activation='relu')),
#model.add(Dropout(0.1)),
model.add(Dense(num_classes, activation='softmax')),
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=1000, batch_size=1000)

i = 0
while i < 0:
    y_pred = model.predict(X_test)
    y_pred_thres = (y_pred > 1)
    y_pred_thres = y_pred_thres * 1
    y_pred2 = y_pred_thres.argmax(axis=1)
    y_test2 = y_test.argmax(axis=1)
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test, y_pred2)
    
    from sklearn.metrics import accuracy_score
    accuracy = accuracy_score(y_test2, y_pred2)
    print(f'accuracyis: {acuuracy} when threshold is: {i}')
    i = i + 0.05

y_pred = model.predict(X_test)
y_pred_thres = (y_pred > 0.15)
y_pred_thres = y_pred_thres * 1
y_pred2 = y_pred_thres.argmax(axis=1)
y_test2 = y_test.argmax(axis=1)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test2, y_pred2) 

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test2, y_pred2)

print(f'accuracy is: {accuracy}')

def baseline_model():
    model = Sequential()
    model.add(Dense(58, input_shape=input_shape, activation='relu'))
    model.add(Dropout(0.1)),
    model.add(Dense(58, activation='relu')),
    model.add(Dropout(0.1)),
    model.add(Dense(58, activation='relu')),
    model.add(Dropout(0.1)),
    model.add(Dense(58, activation='relu')),
    model.add(Dropout(0.1)),
    model.add(Dense(58, activation='relu')),
    #model.add(Dropout(0.1)),
    model.add(Dense(58, activation='relu')),
    #model.add(Dropout(0.1)),
    model.add(Dense(num_classes, activation='softmax')),
    sgd = SGD(learning_rate = 0.01, decay = 1e-6, momentum = 0.9, nesterov = True)
    model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
    return model

estimator = KerasClassifier(model=baseline_model, epochs=1000, batch_size=100)

kfold = KFold(n_splits=5, shuffle=True)
results = cross_val_score(estimator, xs_train, ys_train, cv=kfold)
print("Baseline: %.2f (5.2f%%)" % (results.mean() * 100, results.std() * 100))

In [52]:
from scikeras.wrappers import KerasClassifier

In [49]:
pip install scikeras

Note: you may need to restart the kernel to use updated packages.


In [ ]:
from sklearn.model_selection import StratifiedKFold
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import  SGD
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from scikeras.wrappers import KerasClassifier
import json 
import tensorflow as tf
import numpy as np
import pandas as pd

# define the input shape
input_shape = (999,)
num_classes = 6

with open('training.json', 'r') as f:
    data_dict = json.load(f)

obj = {
    "Hand Close": 0,
    "Thumb": 1,
    "Index": 2,
    "Middle": 3,
    "Ring": 4,
    "Pinky": 5
}
    
# extract the x and y data from the JSON dictionary
xs_train = [[int(x) for x in data['xs'].values()] for data in data_dict['data']]
ys_train = [obj[data['ys']['label']] for data in data_dict['data']]
ys_train = tf.keras.utils.to_categorical(ys_train, num_classes)

xs_train = np.array(xs_train)
ys_train = np.array(ys_train)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(xs_train, ys_train, test_size = 0.25, random_state = 0) 

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X = scaler.transform(xs_train)

dim = 999
dropout = 0.1

model = Sequential()
model.add(Dense(dim, input_shape=input_shape, activation='relu'))
model.add(Dropout(dropout)),
model.add(Dense(dim, activation='relu')),
model.add(Dropout(dropout)),
model.add(Dense(dim, activation='relu')),
model.add(Dropout(dropout)),
model.add(Dense(dim, activation='relu')),
model.add(Dropout(dropout)),
model.add(Dense(dim, activation='relu')),
#model.add(Dropout(dropout)),
model.add(Dense(dim, activation='relu')),
#model.add(Dropout(dropout)),
model.add(Dense(num_classes, activation='softmax')),
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=1000, batch_size=1000)

i = 0
while i < 0:
    y_pred = model.predict(X_test)
    y_pred_thres = (y_pred > 1)
    y_pred_thres = y_pred_thres * 1
    y_pred2 = y_pred_thres.argmax(axis=1)
    y_test2 = y_test.argmax(axis=1)
    from sllearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test, y_pred2)
    
    from sklearn.metrics import accuracy_score
    accuracy = accuracy_score(y_test2, y_pred2)
    print(f'accuracyis: {acuuracy} when threshold is: {i}')
    i = i + 0.05

y_pred = model.predict(X_test)
y_pred_thres = (y_pred > 0.15)
y_pred_thres = y_pred_thres * 1
y_pred2 = y_pred_thres.argmax(axis=1)
y_test2 = y_test.argmax(axis=1)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test2, y_pred2) 

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test2, y_pred2)

print(f'accuracy is: {accuracy}')

def baseline_model():
    model = Sequential()
    model.add(Dense(dim, input_shape=input_shape, activation='relu'))
    model.add(Dropout(dropout)),
    model.add(Dense(dim, activation='relu')),
    model.add(Dropout(dropout)),
    model.add(Dense(dim, activation='relu')),
    model.add(Dropout(dropout)),
    model.add(Dense(dim, activation='relu')),
    model.add(Dropout(dropout)),
    model.add(Dense(dim, activation='relu')),
    #model.add(Dropout(dropout)),
    model.add(Dense(dim, activation='relu')),
    #model.add(Dropout(dropout)),
    model.add(Dense(num_classes, activation='softmax')),
    sgd = SGD(learning_rate = 0.01, decay = 1e-6, momentum = 0.9, nesterov = True)
    model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
    return model

estimator = KerasClassifier(model=baseline_model, epochs=1000, batch_size=100)

kfold = KFold(n_splits=5, shuffle=True)
results = cross_val_score(estimator, xs_train, ys_train, cv=kfold)
print("Baseline: %.2f (5.2f%%)" % (results.mean() * 100, results.std() * 100))

Epoch 1/1000
1/1 [==============================] - 15s 15s/step - loss: 1.7899 - accuracy: 0.1711
Epoch 2/1000
1/1 [==============================] - 0s 167ms/step - loss: 2.2052 - accuracy: 0.2105
Epoch 3/1000
1/1 [==============================] - 0s 194ms/step - loss: 2.0138 - accuracy: 0.1842
Epoch 4/1000
1/1 [==============================] - 0s 170ms/step - loss: 1.8322 - accuracy: 0.1316
Epoch 5/1000
1/1 [==============================] - 0s 166ms/step - loss: 1.7815 - accuracy: 0.2368
Epoch 6/1000
1/1 [==============================] - 0s 203ms/step - loss: 1.7803 - accuracy: 0.2105
Epoch 7/1000
1/1 [==============================] - 0s 179ms/step - loss: 1.7735 - accuracy: 0.2368
Epoch 8/1000
1/1 [==============================] - 0s 177ms/step - loss: 1.7789 - accuracy: 0.1711
Epoch 9/1000
1/1 [==============================] - 0s 170ms/step - loss: 1.7786 - accuracy: 0.2500
Epoch 10/1000
1/1 [==============================] - 0s 202ms/step - loss: 1.7689 - accuracy: 0.2105


1/1 [==============================] - 0s 156ms/step - loss: 0.6372 - accuracy: 0.7237
Epoch 163/1000
1/1 [==============================] - 0s 194ms/step - loss: 0.7588 - accuracy: 0.7368
Epoch 164/1000
1/1 [==============================] - 0s 185ms/step - loss: 0.8291 - accuracy: 0.6053
Epoch 165/1000
1/1 [==============================] - 0s 197ms/step - loss: 0.9029 - accuracy: 0.5658
Epoch 166/1000
1/1 [==============================] - 0s 193ms/step - loss: 0.6279 - accuracy: 0.7763
Epoch 167/1000
1/1 [==============================] - 0s 167ms/step - loss: 0.8832 - accuracy: 0.5921
Epoch 168/1000
1/1 [==============================] - 0s 193ms/step - loss: 0.6321 - accuracy: 0.7895
Epoch 169/1000
1/1 [==============================] - 0s 169ms/step - loss: 0.7107 - accuracy: 0.7237
Epoch 170/1000
1/1 [==============================] - 0s 172ms/step - loss: 0.6907 - accuracy: 0.6711
Epoch 171/1000
1/1 [==============================] - 0s 169ms/step - loss: 0.7037 - accuracy: 0.

1/1 [==============================] - 0s 161ms/step - loss: 0.7933 - accuracy: 0.6842
Epoch 323/1000
1/1 [==============================] - 0s 183ms/step - loss: 0.8329 - accuracy: 0.6316
Epoch 324/1000
1/1 [==============================] - 0s 169ms/step - loss: 0.7707 - accuracy: 0.7368
Epoch 325/1000
1/1 [==============================] - 0s 176ms/step - loss: 0.7550 - accuracy: 0.7368
Epoch 326/1000
1/1 [==============================] - 0s 186ms/step - loss: 0.6646 - accuracy: 0.7763
Epoch 327/1000
1/1 [==============================] - 0s 190ms/step - loss: 0.7564 - accuracy: 0.7237
Epoch 328/1000
1/1 [==============================] - 0s 174ms/step - loss: 0.6817 - accuracy: 0.7105
Epoch 329/1000
1/1 [==============================] - 0s 187ms/step - loss: 0.6609 - accuracy: 0.7763
Epoch 330/1000
1/1 [==============================] - 0s 176ms/step - loss: 0.6303 - accuracy: 0.7895
Epoch 331/1000
1/1 [==============================] - 0s 200ms/step - loss: 0.6179 - accuracy: 0.

1/1 [==============================] - 0s 146ms/step - loss: 0.4452 - accuracy: 0.8684
Epoch 483/1000
1/1 [==============================] - 0s 142ms/step - loss: 0.5320 - accuracy: 0.7895
Epoch 484/1000
1/1 [==============================] - 0s 140ms/step - loss: 0.7710 - accuracy: 0.8026
Epoch 485/1000
1/1 [==============================] - 0s 130ms/step - loss: 0.5545 - accuracy: 0.8289
Epoch 486/1000
1/1 [==============================] - 0s 142ms/step - loss: 0.3495 - accuracy: 0.8947
Epoch 487/1000
1/1 [==============================] - 0s 148ms/step - loss: 0.5022 - accuracy: 0.8026
Epoch 488/1000
1/1 [==============================] - 0s 131ms/step - loss: 0.4677 - accuracy: 0.8553
Epoch 489/1000
1/1 [==============================] - 0s 137ms/step - loss: 0.3662 - accuracy: 0.8816
Epoch 490/1000
1/1 [==============================] - 0s 137ms/step - loss: 0.4111 - accuracy: 0.8684
Epoch 491/1000
1/1 [==============================] - 0s 167ms/step - loss: 0.2783 - accuracy: 0.

1/1 [==============================] - 0s 354ms/step - loss: 1.5015 - accuracy: 0.3553
Epoch 643/1000
1/1 [==============================] - 0s 403ms/step - loss: 1.4355 - accuracy: 0.3816
Epoch 644/1000
1/1 [==============================] - 0s 337ms/step - loss: 1.4988 - accuracy: 0.3553
Epoch 645/1000
1/1 [==============================] - 0s 377ms/step - loss: 1.4373 - accuracy: 0.3553
Epoch 646/1000
1/1 [==============================] - 0s 397ms/step - loss: 1.5146 - accuracy: 0.3158
Epoch 647/1000
1/1 [==============================] - 0s 305ms/step - loss: 1.4597 - accuracy: 0.3553
Epoch 648/1000
1/1 [==============================] - 0s 331ms/step - loss: 1.3972 - accuracy: 0.3553
Epoch 649/1000
1/1 [==============================] - 0s 330ms/step - loss: 1.3907 - accuracy: 0.4211
Epoch 650/1000
1/1 [==============================] - 0s 292ms/step - loss: 1.3768 - accuracy: 0.4079
Epoch 651/1000
1/1 [==============================] - 0s 321ms/step - loss: 1.4391 - accuracy: 0.

1/1 [==============================] - 0s 176ms/step - loss: 1.6781 - accuracy: 0.2632
Epoch 803/1000
1/1 [==============================] - 0s 184ms/step - loss: 1.6763 - accuracy: 0.2632
Epoch 804/1000
1/1 [==============================] - 0s 176ms/step - loss: 1.6745 - accuracy: 0.2632
Epoch 805/1000
1/1 [==============================] - 0s 192ms/step - loss: 1.6740 - accuracy: 0.2632
Epoch 806/1000
1/1 [==============================] - 0s 192ms/step - loss: 1.6774 - accuracy: 0.2632
Epoch 807/1000
1/1 [==============================] - 0s 225ms/step - loss: 1.6781 - accuracy: 0.2632
Epoch 808/1000
1/1 [==============================] - 0s 209ms/step - loss: 1.6779 - accuracy: 0.2632
Epoch 809/1000
1/1 [==============================] - 0s 184ms/step - loss: 1.6747 - accuracy: 0.2632
Epoch 810/1000
1/1 [==============================] - 0s 231ms/step - loss: 1.6760 - accuracy: 0.2632
Epoch 811/1000
1/1 [==============================] - 0s 218ms/step - loss: 1.6756 - accuracy: 0.

1/1 [==============================] - 0s 188ms/step - loss: 1.6775 - accuracy: 0.2632
Epoch 963/1000
1/1 [==============================] - 0s 193ms/step - loss: 1.6766 - accuracy: 0.2632
Epoch 964/1000
1/1 [==============================] - 0s 209ms/step - loss: 1.6801 - accuracy: 0.2632
Epoch 965/1000
1/1 [==============================] - 0s 194ms/step - loss: 1.6770 - accuracy: 0.2632
Epoch 966/1000
1/1 [==============================] - 0s 190ms/step - loss: 1.6771 - accuracy: 0.2632
Epoch 967/1000
1/1 [==============================] - 0s 238ms/step - loss: 1.6786 - accuracy: 0.2632
Epoch 968/1000
1/1 [==============================] - 0s 187ms/step - loss: 1.6771 - accuracy: 0.2632
Epoch 969/1000
1/1 [==============================] - 0s 187ms/step - loss: 1.7053 - accuracy: 0.2500
Epoch 970/1000
1/1 [==============================] - 0s 183ms/step - loss: 1.6736 - accuracy: 0.2632
Epoch 971/1000
1/1 [==============================] - 0s 190ms/step - loss: 1.7063 - accuracy: 0.

1/1 [==============================] - 0s 290ms/step - loss: nan - accuracy: 0.1605
Epoch 126/1000
1/1 [==============================] - 0s 252ms/step - loss: nan - accuracy: 0.1605
Epoch 127/1000
1/1 [==============================] - 0s 267ms/step - loss: nan - accuracy: 0.1605
Epoch 128/1000
1/1 [==============================] - 0s 310ms/step - loss: nan - accuracy: 0.1605
Epoch 129/1000
1/1 [==============================] - 0s 341ms/step - loss: nan - accuracy: 0.1605
Epoch 130/1000
1/1 [==============================] - 0s 349ms/step - loss: nan - accuracy: 0.1605
Epoch 131/1000
1/1 [==============================] - 0s 318ms/step - loss: nan - accuracy: 0.1605
Epoch 132/1000
1/1 [==============================] - 0s 271ms/step - loss: nan - accuracy: 0.1605
Epoch 133/1000
1/1 [==============================] - 0s 285ms/step - loss: nan - accuracy: 0.1605
Epoch 134/1000
1/1 [==============================] - 0s 331ms/step - loss: nan - accuracy: 0.1605
Epoch 135/1000
1/1 [=====